# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        account_login:
            pattern:  ^/account/login$
            anonymous: true

        account:
            pattern: ^/account
            provider: fos_userbundle
            anonymous: false

            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

                login_path: fos_user_security_login
                check_path: fos_user_security_check

            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login

        default:
            anonymous: ~

    access_control:
        - { path: ^/account/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/admin, role: ROLE_ADMIN }
