hetic_app_homepage:
    path:     /
    defaults: { _controller: HETICAppBundle:Home:index }
    
    
hetic_app_cart:
    path:     /cart
    defaults: { _controller: HETICAppBundle:Cart:index }
    
    
hetic_app_confirm:
    path:     /confirm
    defaults: { _controller: HETICAppBundle:Confirm:index }
    
hetic_app_adresse:
    path:     /adresse
    defaults: { _controller: HETICAppBundle:Adresse:index }    
